import type { Metadata } from "next";
import LogoHeader from "@/components/structures/logo-header";
import "./globals.css";
import Footer from "@/components/structures/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <div className="min-h-screen flex flex-col">
          <LogoHeader />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
